const FIRST_TASK_MAX_GRADE = 1
const SECOND_TASK_MAX_GRADE = 5
const THIRD_TASK_MAX_GRADE = 4
const FOURTH_TASK_MAX_GRADE = 10

const TOTAL_TASK_MAX_GRADE = 20

const TASKS_MAX_GRADE = {
    1 : FIRST_TASK_MAX_GRADE,
    2 : SECOND_TASK_MAX_GRADE,
    3 : THIRD_TASK_MAX_GRADE,
    4 : FOURTH_TASK_MAX_GRADE,
    TOTAL_TASK_MAX_GRADE
}

export default TASKS_MAX_GRADE
