const PREPARE_TIMER = 1

const FIRST_TASK_READING_TIMER = 1000
const FIRST_TASK_SPEAKING_TIMER = 90

const SECOND_TASK_READING_TIMER = 90
const SECOND_TASK_CHANGE_TOPIC = 0
const SECOND_TASK_SPEAKING_TIMER = 20

const THIRD_TASK_READING_TIMER = 0
const THIRD_TASK_CHANGE_QUESTION = 0
const THIRD_TASK_SPEAKING_TIMER = 40

const FOURTH_TASK_READING_TIMER = 150
const FOURTH_TASK_SPEAKING_TIMER = 180

const timersConfig = {
    PREPARE_TIMER,
    FIRST_TASK_READING_TIMER,
    FIRST_TASK_SPEAKING_TIMER,
    SECOND_TASK_READING_TIMER,
    SECOND_TASK_CHANGE_TOPIC,
    SECOND_TASK_SPEAKING_TIMER,
    THIRD_TASK_READING_TIMER,
    THIRD_TASK_CHANGE_QUESTION,
    THIRD_TASK_SPEAKING_TIMER,
    FOURTH_TASK_READING_TIMER,
    FOURTH_TASK_SPEAKING_TIMER
}

export default timersConfig